
package Formularios;

import Classes.Dados;
import Classes.Utilidades;
import javax.swing.table.DefaultTableModel;

public class frmpesqProdutos extends javax.swing.JDialog {

    private Dados msDados;
  private DefaultTableModel mTabela;
  private String resposta ="";
    
    public void setDados(Dados msDados){
        this.msDados = msDados;
    }
    
    public String getResposta(){
        return resposta;
    }
    
    private void preencherTabela(){
        String titulos[]= {"ID Produto","Descrição"};
        String registro[]= new String[2];
        mTabela = new DefaultTableModel(null,titulos);
        if(txtpesqprod.getText().equals("")){
        for(int i =0; i<msDados.numeroProdutos();i++){
            
            registro[0]= msDados.getProdutos()[i].getIdProduto();
            registro[1]= msDados.getProdutos()[i].getDescricao();
            mTabela.addRow(registro);
            }
            tblTabela.setModel(mTabela);
            return;
        }
             
            
            if(radiodescricaoproduto.isSelected()){
            for(int i =0; i<msDados.numeroProdutos();i++){    
            if(msDados.getProdutos()[i].getDescricao().startsWith(txtpesqprod.getText())){
            registro[0]= msDados.getProdutos()[i].getIdProduto();
            registro[1]= msDados.getProdutos()[i].getDescricao(); 
            mTabela.addRow(registro);
                }
            }
            tblTabela.setModel(mTabela);
            return;
        }
        if(radioidprod.isSelected()){
            for(int i =0; i<msDados.numeroProdutos();i++){    
            if(msDados.getProdutos()[i].getIdProduto().startsWith(txtpesqprod.getText())){
            registro[0]= msDados.getProdutos()[i].getIdProduto();
            registro[1]= msDados.getProdutos()[i].getDescricao();
            mTabela.addRow(registro);
                }
            }
            tblTabela.setModel(mTabela);
            
        }
    }
    
    
    
    public frmpesqProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bgtipopesq.add(radioidprod);
        bgtipopesq.add(radiodescricaoproduto);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgtipopesq = new javax.swing.ButtonGroup();
        radioidprod = new javax.swing.JRadioButton();
        radiodescricaoproduto = new javax.swing.JRadioButton();
        txtpesqprod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnsair = new javax.swing.JButton();
        btnpesq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        radioidprod.setSelected(true);
        radioidprod.setText("ID Produto");
        radioidprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioidprodActionPerformed(evt);
            }
        });

        radiodescricaoproduto.setText("Descrição");
        radiodescricaoproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiodescricaoprodutoActionPerformed(evt);
            }
        });

        txtpesqprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesqprodActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabela);

        btnsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-fechar-janela-24.png"))); // NOI18N
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        btnpesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar-20.png"))); // NOI18N
        btnpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpesqprod)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioidprod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radiodescricaoproduto)))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnpesq)
                        .addGap(18, 18, 18)
                        .addComponent(btnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioidprod)
                    .addComponent(radiodescricaoproduto))
                .addGap(18, 18, 18)
                .addComponent(txtpesqprod, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpesqprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesqprodActionPerformed
       preencherTabela();
    }//GEN-LAST:event_txtpesqprodActionPerformed

    private void btnpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqActionPerformed
        int num = tblTabela.getRowCount();
        if(num== 0){
        resposta="";
        dispose();
        return;
        }
        for (int i = 0; i < num; i++){
            if(tblTabela.isRowSelected(i)){
            resposta = Utilidades.objectToString(tblTabela.getValueAt(i, 0));           
            dispose();
            return;
            } 
        }
        resposta = Utilidades.objectToString(tblTabela.getValueAt(0, 0));          
        dispose();
    }//GEN-LAST:event_btnpesqActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtpesqprod.requestFocusInWindow();
        preencherTabela();
        
    }//GEN-LAST:event_formWindowOpened

    private void radiodescricaoprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiodescricaoprodutoActionPerformed
        txtpesqprod.setText("");
        txtpesqprod.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radiodescricaoprodutoActionPerformed

    private void radioidprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioidprodActionPerformed
        txtpesqprod.setText("");
        txtpesqprod.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioidprodActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        resposta="";
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpesqProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpesqProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpesqProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpesqProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmpesqProdutos dialog = new frmpesqProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgtipopesq;
    private javax.swing.JButton btnpesq;
    private javax.swing.JButton btnsair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiodescricaoproduto;
    private javax.swing.JRadioButton radioidprod;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtpesqprod;
    // End of variables declaration//GEN-END:variables
}
